/*

 CHESS_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\stefan\Code\GB\Tiles\tile_design_data\chess_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef CHESS_TILEMAP_H
#define CHESS_TILEMAP_H

#define chess_tilemapWidth 20
#define chess_tilemapHeight 18
#define chess_tilemapBank 0

extern const unsigned char chess_tilemap[];

/* End of CHESS_TILEMAP.H */

#endif