/*

 CHESS_WINDOW_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 15
   Tile set      : Z:\home\stefan\Code\GB\Tiles\tile_design_data\chess_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chess_window_tilemapWidth 16
#define chess_window_tilemapHeight 15
#define chess_window_tilemapBank 0

extern unsigned char chess_window_tilemap[];

/* End of CHESS_WINDOW_TILEMAP.H */
