/*

 CHESS_SPRITE_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/
#ifndef CHESS_SPRITE_TILES_H
#define CHESS_SPRITE_TILES_H

/* Bank of tiles. */
#define chess_sprite_tilesBank 0
/* Start of tile array. */
extern const unsigned char chess_sprite_tiles[];

/* End of CHESS_SPRITE_TILES.H */

#endif