/*

 CHESS_RANKLABEL_TILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 1 x 16
   Tile set      : chess_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chess_ranklabel_tilemapWidth 1
#define chess_ranklabel_tilemapHeight 16
#define chess_ranklabel_tilemapBank 0

const unsigned char chess_ranklabel_tilemap[] =
{
  0xCE,0x63,0xCD,0x63,0xCC,0x63,0xCB,0x63,0xCA,0x63,
  0xC9,0x63,0xC8,0x63,0xC7,0x63
};

/* End of CHESS_RANKLABEL_TILEMAP.C */
