/*

 CHESS_FILELABEL_TILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 1
   Tile set      : chess_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chess_filelabel_tilemapWidth 16
#define chess_filelabel_tilemapHeight 1
#define chess_filelabel_tilemapBank 0

const unsigned char chess_filelabel_tilemap[] =
{
  0xAA,0x63,0xAB,0x63,0xAC,0x63,0xAD,0x63,0xAE,0x63,
  0xAF,0x63,0xB0,0x63,0xB1,0x63
};

/* End of CHESS_FILELABEL_TILEMAP.C */
