/*

 CHESS_REPLAY_LABEL_TILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 1
   Tile set      : chess_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define chess_replay_label_tilemapWidth 12
#define chess_replay_label_tilemapHeight 1
#define chess_replay_label_tilemapBank 0

const unsigned char chess_replay_label_tilemap[] =
{
  0xBB,0xAE,0xB9,0xB5,0xAA,0xC2,0x63,0x63,0xB6,0xB8,
  0xAD,0xAE
};

/* End of CHESS_REPLAY_LABEL_TILEMAP.C */
